
INSERT INTO `countries` ( `country_key`, `country_key_alpha3`) VALUES
('af', 'afg'),
('ax', 'ala'),
('al', 'alb'),
('dz', 'dza'),
('as', 'asm'),
('ad', 'and'),
('ao', 'ago'),
('ai', 'aia'),
('aq', ''),
('ag', 'atg'),
('ar', 'arg'),
('am', 'arm'),
('aw', 'abw'),
('au', 'aus'),
('at', 'aut'),
('az', 'aze'),
('bs', 'bhs'),
('bh', 'bhr'),
('bd', 'bgd'),
('bb', 'brb'),
('by', 'blr'),
('be', 'bel'),
('bz', 'blz'),
('bj', 'ben'),
('bm', 'bmu'),
('bt', 'btn'),
('bo', 'bol'),
('bq', 'bes'),
('ba', 'bih'),
('bw', 'bwa'),
('bv', null),
('br', 'bra'),
('io', null),
('bn', 'brn'),
('bg', 'bgr'),
('bf', 'bfa'),
('bi', 'bdi'),
('kh', 'khm'),
('cm', 'cmr'),
('ca', 'can'),
('cv', 'cpv'),
('ky', 'cym'),
('cf', 'caf'),
('td', 'tcd'),
('cl', 'chl'),
('cn', 'chn'),
('cx', null),
('cc', null),
('co', 'col'),
('km', 'com'),
('cg', 'cog'),
('cd', 'cod'),
('ck', 'cok'),
('cr', 'cri'),
('ci', 'civ'),
('hr', 'hrv'),
('cu', 'cub'),
('cw', 'cuw'),
('cy', 'cyp'),
('cz', 'cze'),
('dk', 'dnk'),
('dj', 'dji'),
('dm', 'dma'),
('do', 'dom'),
('ec', 'ecu'),
('eg', 'egy'),
('sv', 'slv'),
('gq', 'gnq'),
('er', 'eri'),
('ee', 'est'),
('et', 'eth'),
('fk', 'flk'),
('fo', 'fro'),
('fj', 'fji'),
('fi', 'fin'),
('fr', 'fra'),
('gf', 'guf'),
('pf', 'pyf'),
('tf', null),
('ga', 'gab'),
('gm', 'gmb'),
('ge', 'geo'),
('de', 'deu'),
('gh', 'gha'),
('gi', 'gib'),
('gr', 'grc'),
('gl', 'grl'),
('gd', 'grd'),
('gp', 'glp'),
('gu', 'gum'),
('gt', 'gtm'),
('gg', 'ggy'),
('gn', 'gin'),
('gw', 'gnb'),
('gy', 'guy'),
('ht', 'hti'),
('hm', null),
('va', 'vat'),
('hn', 'hnd'),
('hk', 'hkg'),
('hu', 'hun'),
('is', 'isl'),
('in', 'ind'),
('id', 'idn'),
('ir', 'irn'),
('iq', 'irq'),
('ie', 'irl'),
('im', 'imn'),
('il', 'isr'),
('it', 'ita'),
('jm', 'jam'),
('jp', 'jpn'),
('je', 'jey'),
('jo', 'jor'),
('kz', 'kaz'),
('ke', 'ken'),
('ki', 'kir'),
('kp', 'prk'),
('kr', 'kor'),
('kw', 'kwt'),
('kg', 'kgz'),
('la', 'lao'),
('lv', 'lva'),
('lb', 'lbn'),
('ls', 'lso'),
('lr', 'lbr'),
('ly', 'lby'),
('li', 'lie'),
('lt', 'ltu'),
('lu', 'lux'),
('mo', 'mac'),
('mk', 'mkd'),
('mg', 'mdg'),
('mw', 'mwi'),
('my', 'mys'),
('mv', 'mdv'),
('ml', 'mli'),
('mt', 'mlt'),
('mh', 'mhl'),
('mq', 'mtq'),
('mr', 'mrt'),
('mu', 'mus'),
('yt', 'myt'),
('mx', 'mex'),
('fm', 'fsm'),
('md', 'mda'),
('mc', 'mco'),
('mn', 'mng'),
('me', 'mne'),
('ms', 'msr'),
('ma', 'mar'),
('mz', 'moz'),
('mm', 'mmr'),
('na', 'nam'),
('nr', 'nru'),
('np', 'npl'),
('nl', 'nld'),
('nc', 'ncl'),
('nz', 'nzl'),
('ni', 'nic'),
('ne', 'ner'),
('ng', 'nga'),
('nu', 'niu'),
('nf', 'nfk'),
('mp', 'mnp'),
('no', 'nor'),
('om', 'omn'),
('pk', 'pak'),
('pw', 'plw'),
('ps', 'pse'),
('pa', 'pan'),
('pg', 'png'),
('py', 'pry'),
('pe', 'per'),
('ph', 'phl'),
('pn', 'pcn'),
('pl', 'pol'),
('pt', 'prt'),
('pr', 'pri'),
('qa', 'qat'),
('re', 'reu'),
('ro', 'rou'),
('ru', 'rus'),
('rw', 'rwa'),
('bl', 'blm'),
('sh', 'shn'),
('kn', 'kna'),
('lc', 'lca'),
('mf', 'maf'),
('pm', 'spm'),
('vc', 'vct'),
('ws', 'wsm'),
('sm', 'smr'),
('st', 'stp'),
('sa', 'sau'),
('sn', 'sen'),
('rs', 'srb'),
('sc', 'syc'),
('sl', 'sle'),
('sg', 'sgp'),
('sx', 'sxm'),
('sk', 'svk'),
('si', 'svn'),
('sb', 'slb'),
('so', 'som'),
('za', 'zaf'),
('gs', null),
('ss', 'ssd'),
('es', 'esp'),
('lk', 'lka'),
('sd', 'sdn'),
('sr', 'sur'),
('sj', 'sjm'),
('sz', 'swz'),
('se', 'swe'),
('ch', 'che'),
('sy', 'syr'),
('tw', null),
('tj', 'tjk'),
('tz', 'tza'),
('th', 'tha'),
('tl', 'tls'),
('tg', 'tgo'),
('tk', 'tkl'),
('to', 'ton'),
('tt', 'tto'),
('tn', 'tun'),
('tr', 'tur'),
('tm', 'tkm'),
('tc', 'tca'),
('tv', 'tuv'),
('ug', 'uga'),
('ua', 'ukr'),
('ae', 'are'),
('gb', 'gbr'),
('us', 'usa'),
('um', null),
('uy', 'ury'),
('uz', 'uzb'),
('vu', 'vut'),
('ve', 'ven'),
('vn', 'vnm'),
('vg', 'vgb'),
('vi', 'vir'),
('wf', 'wlf'),
('eh', 'esh'),
('ye', 'yem'),
('zm', 'zmb'),
('zw', 'zwe');


INSERT INTO `countries_translation` ( `country_key`, `name`, `lang`) VALUES
('af', 'Afghanistan', 'en'),
('af', 'Afghanistan', 'fr'),
('af', 'Afghanistan', 'nl'),
('ax', 'Aland Islands', 'en'),
('ax', 'Aland Islands', 'fr'),
('ax', 'Aland Islands', 'nl'),
('al', 'Albania', 'en'),
('al', 'Albania', 'fr'),
('al', 'Albania', 'nl'),
('dz', 'Algeria', 'en'),
('dz', 'Algeria', 'fr'),
('dz', 'Algeria', 'nl'),
('as', 'American Samoa', 'en'),
('as', 'American Samoa', 'fr'),
('as', 'American Samoa', 'nl'),
('ad', 'Andorra', 'en'),
('ad', 'Andorra', 'fr'),
('ad', 'Andorra', 'nl'),
('ao', 'Angola', 'en'),
('ao', 'Angola', 'fr'),
('ao', 'Angola', 'nl'),
('ai', 'Anguilla', 'en'),
('ai', 'Anguilla', 'fr'),
('ai', 'Anguilla', 'nl'),
('aq', 'Antarctica', 'en'),
('aq', 'Antarctica', 'fr'),
('aq', 'Antarctica', 'nl'),
('ag', 'Antigua and Barbuda', 'en'),
('ag', 'Antigua and Barbuda', 'fr'),
('ag', 'Antigua and Barbuda', 'nl'),
('ar', 'Argentina', 'en'),
('ar', 'Argentina', 'fr'),
('ar', 'Argentina', 'nl'),
('am', 'Armenia', 'en'),
('am', 'Armenia', 'fr'),
('am', 'Armenia', 'nl'),
('aw', 'Aruba', 'en'),
('aw', 'Aruba', 'fr'),
('aw', 'Aruba', 'nl'),
('au', 'Australia', 'en'),
('au', 'Australia', 'fr'),
('au', 'Australia', 'nl'),
('at', 'Austria', 'en'),
('at', 'Austria', 'fr'),
('at', 'Austria', 'nl'),
('az', 'Azerbaijan', 'en'),
('az', 'Azerbaijan', 'fr'),
('az', 'Azerbaijan', 'nl'),
('bs', 'Bahamas', 'en'),
('bs', 'Bahamas', 'fr'),
('bs', 'Bahamas', 'nl'),
('bh', 'Bahrain', 'en'),
('bh', 'Bahrain', 'fr'),
('bh', 'Bahrain', 'nl'),
('bd', 'Bangladesh', 'en'),
('bd', 'Bangladesh', 'fr'),
('bd', 'Bangladesh', 'nl'),
('bb', 'Barbados', 'en'),
('bb', 'Barbados', 'fr'),
('bb', 'Barbados', 'nl'),
('by', 'Belarus', 'en'),
('by', 'Belarus', 'fr'),
('by', 'Belarus', 'nl'),
('be', 'Belgium', 'en'),
('be', 'Belgique', 'fr'),
('be', 'Belgium', 'nl'),
('bz', 'Belize', 'en'),
('bz', 'Belize', 'fr'),
('bz', 'Belize', 'nl'),
('bj', 'Benin', 'en'),
('bj', 'Benin', 'fr'),
('bj', 'Benin', 'nl'),
('bm', 'Bermuda', 'en'),
('bm', 'Bermuda', 'fr'),
('bm', 'Bermuda', 'nl'),
('bt', 'Bhutan', 'en'),
('bt', 'Bhutan', 'fr'),
('bt', 'Bhutan', 'nl'),
('bo', 'Bolivia, Plurinational State of', 'en'),
('bo', 'Bolivia, Plurinational State of', 'fr'),
('bo', 'Bolivia, Plurinational State of', 'nl'),
('bq', 'Bonaire, Sint Eustatius and Saba', 'en'),
('bq', 'Bonaire, Sint Eustatius and Saba', 'fr'),
('bq', 'Bonaire, Sint Eustatius and Saba', 'nl'),
('ba', 'Bosnia and Herzegovina', 'en'),
('ba', 'Bosnia and Herzegovina', 'fr'),
('ba', 'Bosnia and Herzegovina', 'nl'),
('bw', 'Botswana', 'en'),
('bw', 'Botswana', 'fr'),
('bw', 'Botswana', 'nl'),
('bv', 'Bouvet Island', 'en'),
('bv', 'Bouvet Island', 'fr'),
('bv', 'Bouvet Island', 'nl'),
('br', 'Brazil', 'en'),
('br', 'Brazil', 'fr'),
('br', 'Brazil', 'nl'),
('io', 'British Indian Ocean Territory', 'en'),
('io', 'British Indian Ocean Territory', 'fr'),
('io', 'British Indian Ocean Territory', 'nl'),
('bn', 'Brunei Darussalam', 'en'),
('bn', 'Brunei Darussalam', 'fr'),
('bn', 'Brunei Darussalam', 'nl'),
('bg', 'Bulgaria', 'en'),
('bg', 'Bulgaria', 'fr'),
('bg', 'Bulgaria', 'nl'),
('bf', 'Burkina Faso', 'en'),
('bf', 'Burkina Faso', 'fr'),
('bf', 'Burkina Faso', 'nl'),
('bi', 'Burundi', 'en'),
('bi', 'Burundi', 'fr'),
('bi', 'Burundi', 'nl'),
('kh', 'Cambodia', 'en'),
('kh', 'Cambodia', 'fr'),
('kh', 'Cambodia', 'nl'),
('cm', 'Cameroon', 'en'),
('cm', 'Cameroon', 'fr'),
('cm', 'Cameroon', 'nl'),
('ca', 'Canada', 'en'),
('ca', 'Canada', 'fr'),
('ca', 'Canada', 'nl'),
('cv', 'Cape Verde', 'en'),
('cv', 'Cape Verde', 'fr'),
('cv', 'Cape Verde', 'nl'),
('ky', 'Cayman Islands', 'en'),
('ky', 'Cayman Islands', 'fr'),
('ky', 'Cayman Islands', 'nl'),
('cf', 'Central African Republic', 'en'),
('cf', 'Central African Republic', 'fr'),
('cf', 'Central African Republic', 'nl'),
('td', 'Chad', 'en'),
('td', 'Chad', 'fr'),
('td', 'Chad', 'nl'),
('cl', 'Chile', 'en'),
('cl', 'Chile', 'fr'),
('cl', 'Chile', 'nl'),
('cn', 'China', 'en'),
('cn', 'China', 'fr'),
('cn', 'China', 'nl'),
('cx', 'Christmas Island', 'en'),
('cx', 'Christmas Island', 'fr'),
('cx', 'Christmas Island', 'nl'),
('cc', 'Cocos array(Keeling) Islands', 'en'),
('cc', 'Cocos array(Keeling) Islands', 'fr'),
('cc', 'Cocos array(Keeling) Islands', 'nl'),
('co', 'Colombia', 'en'),
('co', 'Colombia', 'fr'),
('co', 'Colombia', 'nl'),
('km', 'Comoros', 'en'),
('km', 'Comoros', 'fr'),
('km', 'Comoros', 'nl'),
('cg', 'Congo', 'en'),
('cg', 'Congo', 'fr'),
('cg', 'Congo', 'nl'),
('cd', 'Congo, The Democratic Republic of the', 'en'),
('cd', 'Congo, The Democratic Republic of the', 'fr'),
('cd', 'Congo, The Democratic Republic of the', 'nl'),
('ck', 'Cook Islands', 'en'),
('ck', 'Cook Islands', 'fr'),
('ck', 'Cook Islands', 'nl'),
('cr', 'Costa Rica', 'en'),
('cr', 'Costa Rica', 'fr'),
('cr', 'Costa Rica', 'nl'),
('ci', 'Cote d''Ivoire', 'en'),
('ci', 'Cote d''Ivoire', 'fr'),
('ci', 'Cote d''Ivoire', 'nl'),
('hr', 'Croatia', 'en'),
('hr', 'Croatia', 'fr'),
('hr', 'Croatia', 'nl'),
('cu', 'Cuba', 'en'),
('cu', 'Cuba', 'fr'),
('cu', 'Cuba', 'nl'),
('cw', 'Curacao', 'en'),
('cw', 'Curacao', 'fr'),
('cw', 'Curacao', 'nl'),
('cy', 'Cyprus', 'en'),
('cy', 'Cyprus', 'fr'),
('cy', 'Cyprus', 'nl'),
('cz', 'Czech Republic', 'en'),
('cz', 'Czech Republic', 'fr'),
('cz', 'Czech Republic', 'nl'),
('dk', 'Denmark', 'en'),
('dk', 'Denmark', 'fr'),
('dk', 'Denmark', 'nl'),
('dj', 'Djibouti', 'en'),
('dj', 'Djibouti', 'fr'),
('dj', 'Djibouti', 'nl'),
('dm', 'Dominica', 'en'),
('dm', 'Dominica', 'fr'),
('dm', 'Dominica', 'nl'),
('do', 'Dominican Republic', 'en'),
('do', 'Dominican Republic', 'fr'),
('do', 'Dominican Republic', 'nl'),
('ec', 'Ecuador', 'en'),
('ec', 'Ecuador', 'fr'),
('ec', 'Ecuador', 'nl'),
('eg', 'Egypt', 'en'),
('eg', 'Egypt', 'fr'),
('eg', 'Egypt', 'nl'),
('sv', 'El Salvador', 'en'),
('sv', 'El Salvador', 'fr'),
('sv', 'El Salvador', 'nl'),
('gq', 'Equatorial Guinea', 'en'),
('gq', 'Equatorial Guinea', 'fr'),
('gq', 'Equatorial Guinea', 'nl'),
('er', 'Eritrea', 'en'),
('er', 'Eritrea', 'fr'),
('er', 'Eritrea', 'nl'),
('ee', 'Estonia', 'en'),
('ee', 'Estonia', 'fr'),
('ee', 'Estonia', 'nl'),
('et', 'Ethiopia', 'en'),
('et', 'Ethiopia', 'fr'),
('et', 'Ethiopia', 'nl'),
('fk', 'Falkland Islands array(Malvinas)', 'en'),
('fk', 'Falkland Islands array(Malvinas)', 'fr'),
('fk', 'Falkland Islands array(Malvinas)', 'nl'),
('fo', 'Faroe Islands', 'en'),
('fo', 'Faroe Islands', 'fr'),
('fo', 'Faroe Islands', 'nl'),
('fj', 'Fiji', 'en'),
('fj', 'Fiji', 'fr'),
('fj', 'Fiji', 'nl'),
('fi', 'Finland', 'en'),
('fi', 'Finland', 'fr'),
('fi', 'Finland', 'nl'),
('fr', 'France', 'en'),
('fr', 'France', 'fr'),
('fr', 'France', 'nl'),
('gf', 'French Guiana', 'en'),
('gf', 'French Guiana', 'fr'),
('gf', 'French Guiana', 'nl'),
('pf', 'French Polynesia', 'en'),
('pf', 'French Polynesia', 'fr'),
('pf', 'French Polynesia', 'nl'),
('tf', 'French Southern Territories', 'en'),
('tf', 'French Southern Territories', 'fr'),
('tf', 'French Southern Territories', 'nl'),
('ga', 'Gabon', 'en'),
('ga', 'Gabon', 'fr'),
('ga', 'Gabon', 'nl'),
('gm', 'Gambia', 'en'),
('gm', 'Gambia', 'fr'),
('gm', 'Gambia', 'nl'),
('ge', 'Georgia', 'en'),
('ge', 'Georgia', 'fr'),
('ge', 'Georgia', 'nl'),
('de', 'Germany', 'en'),
('de', 'Germany', 'fr'),
('de', 'Germany', 'nl'),
('gh', 'Ghana', 'en'),
('gh', 'Ghana', 'fr'),
('gh', 'Ghana', 'nl'),
('gi', 'Gibraltar', 'en'),
('gi', 'Gibraltar', 'fr'),
('gi', 'Gibraltar', 'nl'),
('gr', 'Greece', 'en'),
('gr', 'Greece', 'fr'),
('gr', 'Greece', 'nl'),
('gl', 'Greenland', 'en'),
('gl', 'Greenland', 'fr'),
('gl', 'Greenland', 'nl'),
('gd', 'Grenada', 'en'),
('gd', 'Grenada', 'fr'),
('gd', 'Grenada', 'nl'),
('gp', 'Guadeloupe', 'en'),
('gp', 'Guadeloupe', 'fr'),
('gp', 'Guadeloupe', 'nl'),
('gu', 'Guam', 'en'),
('gu', 'Guam', 'fr'),
('gu', 'Guam', 'nl'),
('gt', 'Guatemala', 'en'),
('gt', 'Guatemala', 'fr'),
('gt', 'Guatemala', 'nl'),
('gg', 'Guernsey', 'en'),
('gg', 'Guernsey', 'fr'),
('gg', 'Guernsey', 'nl'),
('gn', 'Guinea', 'en'),
('gn', 'Guinea', 'fr'),
('gn', 'Guinea', 'nl'),
('gw', 'Guinea-Bissau', 'en'),
('gw', 'Guinea-Bissau', 'fr'),
('gw', 'Guinea-Bissau', 'nl'),
('gy', 'Guyana', 'en'),
('gy', 'Guyana', 'fr'),
('gy', 'Guyana', 'nl'),
('ht', 'Haiti', 'en'),
('ht', 'Haiti', 'fr'),
('ht', 'Haiti', 'nl'),
('hm', 'Heard Island and McDonald Islands', 'en'),
('hm', 'Heard Island and McDonald Islands', 'fr'),
('hm', 'Heard Island and McDonald Islands', 'nl'),
('va', 'Holy See array(Vatican City State)', 'en'),
('va', 'Holy See array(Vatican City State)', 'fr'),
('va', 'Holy See array(Vatican City State)', 'nl'),
('hn', 'Honduras', 'en'),
('hn', 'Honduras', 'fr'),
('hn', 'Honduras', 'nl'),
('hk', 'Hong Kong', 'en'),
('hk', 'Hong Kong', 'fr'),
('hk', 'Hong Kong', 'nl'),
('hu', 'Hungary', 'en'),
('hu', 'Hungary', 'fr'),
('hu', 'Hungary', 'nl'),
('is', 'Iceland', 'en'),
('is', 'Iceland', 'fr'),
('is', 'Iceland', 'nl'),
('in', 'India', 'en'),
('in', 'India', 'fr'),
('in', 'India', 'nl'),
('id', 'Indonesia', 'en'),
('id', 'Indonesia', 'fr'),
('id', 'Indonesia', 'nl'),
('ir', 'Iran, Islamic Republic of', 'en'),
('ir', 'Iran, Islamic Republic of', 'fr'),
('ir', 'Iran, Islamic Republic of', 'nl'),
('iq', 'Iraq', 'en'),
('iq', 'Iraq', 'fr'),
('iq', 'Iraq', 'nl'),
('ie', 'Ireland', 'en'),
('ie', 'Ireland', 'fr'),
('ie', 'Ireland', 'nl'),
('im', 'Isle of Man', 'en'),
('im', 'Isle of Man', 'fr'),
('im', 'Isle of Man', 'nl'),
('il', 'Israel', 'en'),
('il', 'Israel', 'fr'),
('il', 'Israel', 'nl'),
('it', 'Italy', 'en'),
('it', 'Italy', 'fr'),
('it', 'Italy', 'nl'),
('jm', 'Jamaica', 'en'),
('jm', 'Jamaica', 'fr'),
('jm', 'Jamaica', 'nl'),
('jp', 'Japan', 'en'),
('jp', 'Japan', 'fr'),
('jp', 'Japan', 'nl'),
('je', 'Jersey', 'en'),
('je', 'Jersey', 'fr'),
('je', 'Jersey', 'nl'),
('jo', 'Jordan', 'en'),
('jo', 'Jordan', 'fr'),
('jo', 'Jordan', 'nl'),
('kz', 'Kazakhstan', 'en'),
('kz', 'Kazakhstan', 'fr'),
('kz', 'Kazakhstan', 'nl'),
('ke', 'Kenya', 'en'),
('ke', 'Kenya', 'fr'),
('ke', 'Kenya', 'nl'),
('ki', 'Kiribati', 'en'),
('ki', 'Kiribati', 'fr'),
('ki', 'Kiribati', 'nl'),
('kp', 'Korea, Democratic People''s Republic of', 'en'),
( 'kp', 'Korea, Democratic People''s Republic of', 'fr'),
( 'kp', 'Korea, Democratic People''s Republic of', 'nl'),
('kr', 'Korea, Republic of', 'en'),
('kr', 'Korea, Republic of', 'fr'),
('kr', 'Korea, Republic of', 'nl'),
('kw', 'Kuwait', 'en'),
('kw', 'Kuwait', 'fr'),
('kw', 'Kuwait', 'nl'),
('kg', 'Kyrgyzstan', 'en'),
('kg', 'Kyrgyzstan', 'fr'),
('kg', 'Kyrgyzstan', 'nl'),
( 'la', 'Lao People''s Democratic Republic', 'en'),
( 'la', 'Lao People''s Democratic Republic', 'fr'),
( 'la', 'Lao People''s Democratic Republic', 'nl'),
('lv', 'Latvia', 'en'),
('lv', 'Latvia', 'fr'),
('lv', 'Latvia', 'nl'),
('lb', 'Lebanon', 'en'),
('lb', 'Lebanon', 'fr'),
('lb', 'Lebanon', 'nl'),
('ls', 'Lesotho', 'en'),
('ls', 'Lesotho', 'fr'),
('ls', 'Lesotho', 'nl'),
('lr', 'Liberia', 'en'),
('lr', 'Liberia', 'fr'),
('lr', 'Liberia', 'nl'),
('ly', 'Libyan Arab Jamahiriya', 'en'),
('ly', 'Libyan Arab Jamahiriya', 'fr'),
('ly', 'Libyan Arab Jamahiriya', 'nl'),
('li', 'Liechtenstein', 'en'),
('li', 'Liechtenstein', 'fr'),
('li', 'Liechtenstein', 'nl'),
('lt', 'Lithuania', 'en'),
('lt', 'Lithuania', 'fr'),
('lt', 'Lithuania', 'nl'),
('lu', 'Luxembourg', 'en'),
('lu', 'Luxembourg', 'fr'),
('lu', 'Luxembourg', 'nl'),
('mo', 'Macao', 'en'),
('mo', 'Macao', 'fr'),
('mo', 'Macao', 'nl'),
('mk', 'Macedonia, The former Yugoslav Republic of', 'en'),
('mk', 'Macedonia, The former Yugoslav Republic of', 'fr'),
('mk', 'Macedonia, The former Yugoslav Republic of', 'nl'),
('mg', 'Madagascar', 'en'),
('mg', 'Madagascar', 'fr'),
('mg', 'Madagascar', 'nl'),
('mw', 'Malawi', 'en'),
('mw', 'Malawi', 'fr'),
('mw', 'Malawi', 'nl'),
('my', 'Malaysia', 'en'),
('my', 'Malaysia', 'fr'),
('my', 'Malaysia', 'nl'),
('mv', 'Maldives', 'en'),
('mv', 'Maldives', 'fr'),
('mv', 'Maldives', 'nl'),
('ml', 'Mali', 'en'),
('ml', 'Mali', 'fr'),
('ml', 'Mali', 'nl'),
('mt', 'Malta', 'en'),
('mt', 'Malta', 'fr'),
('mt', 'Malta', 'nl'),
('mh', 'Marshall Islands', 'en'),
('mh', 'Marshall Islands', 'fr'),
('mh', 'Marshall Islands', 'nl'),
('mq', 'Martinique', 'en'),
('mq', 'Martinique', 'fr'),
('mq', 'Martinique', 'nl'),
('mr', 'Mauritania', 'en'),
('mr', 'Mauritania', 'fr'),
('mr', 'Mauritania', 'nl'),
('mu', 'Mauritius', 'en'),
('mu', 'Mauritius', 'fr'),
('mu', 'Mauritius', 'nl'),
('yt', 'Mayotte', 'en'),
('yt', 'Mayotte', 'fr'),
('yt', 'Mayotte', 'nl'),
('mx', 'Mexico', 'en'),
('mx', 'Mexico', 'fr'),
('mx', 'Mexico', 'nl'),
('fm', 'Micronesia, Federated States of', 'en'),
('fm', 'Micronesia, Federated States of', 'fr'),
('fm', 'Micronesia, Federated States of', 'nl'),
('md', 'Moldova, Republic of', 'en'),
('md', 'Moldova, Republic of', 'fr'),
('md', 'Moldova, Republic of', 'nl'),
('mc', 'Monaco', 'en'),
('mc', 'Monaco', 'fr'),
('mc', 'Monaco', 'nl'),
('mn', 'Mongolia', 'en'),
('mn', 'Mongolia', 'fr'),
('mn', 'Mongolia', 'nl'),
('me', 'Montenegro', 'en'),
('me', 'Montenegro', 'fr'),
('me', 'Montenegro', 'nl'),
('ms', 'Montserrat', 'en'),
('ms', 'Montserrat', 'fr'),
('ms', 'Montserrat', 'nl'),
('ma', 'Morocco', 'en'),
('ma', 'Morocco', 'fr'),
('ma', 'Morocco', 'nl'),
('mz', 'Mozambique', 'en'),
('mz', 'Mozambique', 'fr'),
('mz', 'Mozambique', 'nl'),
('mm', 'Myanmar', 'en'),
('mm', 'Myanmar', 'fr'),
('mm', 'Myanmar', 'nl'),
('na', 'Namibia', 'en'),
('na', 'Namibia', 'fr'),
('na', 'Namibia', 'nl'),
('nr', 'Nauru', 'en'),
('nr', 'Nauru', 'fr'),
('nr', 'Nauru', 'nl'),
('np', 'Nepal', 'en'),
('np', 'Nepal', 'fr'),
('np', 'Nepal', 'nl'),
('nl', 'Netherlands', 'en'),
('nl', 'Netherlands', 'fr'),
('nl', 'Netherlands', 'nl'),
('nc', 'New Caledonia', 'en'),
('nc', 'New Caledonia', 'fr'),
('nc', 'New Caledonia', 'nl'),
('nz', 'New Zealand', 'en'),
('nz', 'New Zealand', 'fr'),
('nz', 'New Zealand', 'nl'),
('ni', 'Nicaragua', 'en'),
('ni', 'Nicaragua', 'fr'),
('ni', 'Nicaragua', 'nl'),
('ne', 'Niger', 'en'),
('ne', 'Niger', 'fr'),
('ne', 'Niger', 'nl'),
('ng', 'Nigeria', 'en'),
('ng', 'Nigeria', 'fr'),
('ng', 'Nigeria', 'nl'),
('nu', 'Niue', 'en'),
('nu', 'Niue', 'fr'),
('nu', 'Niue', 'nl'),
('nf', 'Norfolk Island', 'en'),
('nf', 'Norfolk Island', 'fr'),
('nf', 'Norfolk Island', 'nl'),
('mp', 'Northern Mariana Islands', 'en'),
('mp', 'Northern Mariana Islands', 'fr'),
('mp', 'Northern Mariana Islands', 'nl'),
('no', 'Norway', 'en'),
('no', 'Norway', 'fr'),
('no', 'Norway', 'nl'),
('om', 'Oman', 'en'),
('om', 'Oman', 'fr'),
('om', 'Oman', 'nl'),
('pk', 'Pakistan', 'en'),
('pk', 'Pakistan', 'fr'),
('pk', 'Pakistan', 'nl'),
('pw', 'Palau', 'en'),
('pw', 'Palau', 'fr'),
('pw', 'Palau', 'nl'),
('ps', 'Palestinian Territory, Occupied', 'en'),
('ps', 'Palestinian Territory, Occupied', 'fr'),
('ps', 'Palestinian Territory, Occupied', 'nl'),
('pa', 'Panama', 'en'),
('pa', 'Panama', 'fr'),
('pa', 'Panama', 'nl'),
('pg', 'Papua New Guinea', 'en'),
('pg', 'Papua New Guinea', 'fr'),
('pg', 'Papua New Guinea', 'nl'),
('py', 'Paraguay', 'en'),
('py', 'Paraguay', 'fr'),
('py', 'Paraguay', 'nl'),
('pe', 'Peru', 'en'),
('pe', 'Peru', 'fr'),
('pe', 'Peru', 'nl'),
('ph', 'Philippines', 'en'),
('ph', 'Philippines', 'fr'),
('ph', 'Philippines', 'nl'),
('pn', 'Pitcairn', 'en'),
('pn', 'Pitcairn', 'fr'),
('pn', 'Pitcairn', 'nl'),
('pl', 'Poland', 'en'),
('pl', 'Poland', 'fr'),
('pl', 'Poland', 'nl'),
('pt', 'Portugal', 'en'),
('pt', 'Portugal', 'fr'),
('pt', 'Portugal', 'nl'),
('pr', 'Puerto Rico', 'en'),
('pr', 'Puerto Rico', 'fr'),
('pr', 'Puerto Rico', 'nl'),
('qa', 'Qatar', 'en'),
('qa', 'Qatar', 'fr'),
('qa', 'Qatar', 'nl'),
('re', 'Reunion', 'en'),
('re', 'Reunion', 'fr'),
('re', 'Reunion', 'nl'),
('ro', 'Romania', 'en'),
('ro', 'Romania', 'fr'),
('ro', 'Romania', 'nl'),
('ru', 'Russian Federation', 'en'),
('ru', 'Russian Federation', 'fr'),
('ru', 'Russian Federation', 'nl'),
('rw', 'Rwanda', 'en'),
('rw', 'Rwanda', 'fr'),
('rw', 'Rwanda', 'nl'),
('bl', 'Saint Barthelemy', 'en'),
('bl', 'Saint Barthelemy', 'fr'),
('bl', 'Saint Barthelemy', 'nl'),
('sh', 'Saint Helena, Ascension and Tristan Da Cunha', 'en'),
('sh', 'Saint Helena, Ascension and Tristan Da Cunha', 'fr'),
('sh', 'Saint Helena, Ascension and Tristan Da Cunha', 'nl'),
('kn', 'Saint Kitts and Nevis', 'en'),
('kn', 'Saint Kitts and Nevis', 'fr'),
('kn', 'Saint Kitts and Nevis', 'nl'),
('lc', 'Saint Lucia', 'en'),
('lc', 'Saint Lucia', 'fr'),
('lc', 'Saint Lucia', 'nl'),
('mf', 'Saint Martin array(French Part)', 'en'),
('mf', 'Saint Martin array(French Part)', 'fr'),
('mf', 'Saint Martin array(French Part)', 'nl'),
('pm', 'Saint Pierre and Miquelon', 'en'),
('pm', 'Saint Pierre and Miquelon', 'fr'),
('pm', 'Saint Pierre and Miquelon', 'nl'),
('vc', 'Saint Vincent and The Grenadines', 'en'),
('vc', 'Saint Vincent and The Grenadines', 'fr'),
('vc', 'Saint Vincent and The Grenadines', 'nl'),
('ws', 'Samoa', 'en'),
('ws', 'Samoa', 'fr'),
('ws', 'Samoa', 'nl'),
('sm', 'San Marino', 'en'),
('sm', 'San Marino', 'fr'),
('sm', 'San Marino', 'nl'),
('st', 'Sao Tome and Principe', 'en'),
('st', 'Sao Tome and Principe', 'fr'),
('st', 'Sao Tome and Principe', 'nl'),
('sa', 'Saudi Arabia', 'en'),
('sa', 'Saudi Arabia', 'fr'),
('sa', 'Saudi Arabia', 'nl'),
('sn', 'Senegal', 'en'),
('sn', 'Senegal', 'fr'),
('sn', 'Senegal', 'nl'),
('rs', 'Serbia', 'en'),
('rs', 'Serbia', 'fr'),
('rs', 'Serbia', 'nl'),
('sc', 'Seychelles', 'en'),
('sc', 'Seychelles', 'fr'),
('sc', 'Seychelles', 'nl'),
('sl', 'Sierra Leone', 'en'),
('sl', 'Sierra Leone', 'fr'),
('sl', 'Sierra Leone', 'nl'),
('sg', 'Singapore', 'en'),
('sg', 'Singapore', 'fr'),
('sg', 'Singapore', 'nl'),
('sx', 'Sint Maarten array(Dutch Part)', 'en'),
('sx', 'Sint Maarten array(Dutch Part)', 'fr'),
('sx', 'Sint Maarten array(Dutch Part)', 'nl'),
('sk', 'Slovakia', 'en'),
('sk', 'Slovakia', 'fr'),
('sk', 'Slovakia', 'nl'),
('si', 'Slovenia', 'en'),
('si', 'Slovenia', 'fr'),
('si', 'Slovenia', 'nl'),
('sb', 'Solomon Islands', 'en'),
('sb', 'Solomon Islands', 'fr'),
('sb', 'Solomon Islands', 'nl'),
('so', 'Somalia', 'en'),
('so', 'Somalia', 'fr'),
('so', 'Somalia', 'nl'),
('za', 'South Africa', 'en'),
('za', 'South Africa', 'fr'),
('za', 'South Africa', 'nl'),
('gs', 'South Georgia and The South Sandwich Islands', 'en'),
('gs', 'South Georgia and The South Sandwich Islands', 'fr'),
('gs', 'South Georgia and The South Sandwich Islands', 'nl'),
('ss', 'South Sudan', 'en'),
('ss', 'South Sudan', 'fr'),
('ss', 'South Sudan', 'nl'),
('es', 'Spain', 'en'),
('es', 'Spain', 'fr'),
('es', 'Spain', 'nl'),
('lk', 'Sri Lanka', 'en'),
('lk', 'Sri Lanka', 'fr'),
('lk', 'Sri Lanka', 'nl'),
('sd', 'Sudan', 'en'),
('sd', 'Sudan', 'fr'),
('sd', 'Sudan', 'nl'),
('sr', 'Suriname', 'en'),
('sr', 'Suriname', 'fr'),
('sr', 'Suriname', 'nl'),
('sj', 'Svalbard and Jan Mayen', 'en'),
('sj', 'Svalbard and Jan Mayen', 'fr'),
('sj', 'Svalbard and Jan Mayen', 'nl'),
('sz', 'Swaziland', 'en'),
('sz', 'Swaziland', 'fr'),
('sz', 'Swaziland', 'nl'),
('se', 'Sweden', 'en'),
('se', 'Sweden', 'fr'),
('se', 'Sweden', 'nl'),
('ch', 'Switzerland', 'en'),
('ch', 'Switzerland', 'fr'),
('ch', 'Switzerland', 'nl'),
('sy', 'Syrian Arab Republic', 'en'),
('sy', 'Syrian Arab Republic', 'fr'),
('sy', 'Syrian Arab Republic', 'nl'),
('tw', 'Taiwan, Province of China', 'en'),
('tw', 'Taiwan, Province of China', 'fr'),
('tw', 'Taiwan, Province of China', 'nl'),
('tj', 'Tajikistan', 'en'),
('tj', 'Tajikistan', 'fr'),
('tj', 'Tajikistan', 'nl'),
('tz', 'Tanzania, United Republic of', 'en'),
('tz', 'Tanzania, United Republic of', 'fr'),
('tz', 'Tanzania, United Republic of', 'nl'),
('th', 'Thailand', 'en'),
('th', 'Thailand', 'fr'),
('th', 'Thailand', 'nl'),
('tl', 'Timor-Leste', 'en'),
('tl', 'Timor-Leste', 'fr'),
('tl', 'Timor-Leste', 'nl'),
('tg', 'Togo', 'en'),
('tg', 'Togo', 'fr'),
('tg', 'Togo', 'nl'),
('tk', 'Tokelau', 'en'),
('tk', 'Tokelau', 'fr'),
('tk', 'Tokelau', 'nl'),
('to', 'Tonga', 'en'),
('to', 'Tonga', 'fr'),
('to', 'Tonga', 'nl'),
('tt', 'Trinidad and Tobago', 'en'),
('tt', 'Trinidad and Tobago', 'fr'),
('tt', 'Trinidad and Tobago', 'nl'),
('tn', 'Tunisia', 'en'),
('tn', 'Tunisia', 'fr'),
('tn', 'Tunisia', 'nl'),
('tr', 'Turkey', 'en'),
('tr', 'Turkey', 'fr'),
('tr', 'Turkey', 'nl'),
('tm', 'Turkmenistan', 'en'),
('tm', 'Turkmenistan', 'fr'),
('tm', 'Turkmenistan', 'nl'),
('tc', 'Turks and Caicos Islands', 'en'),
('tc', 'Turks and Caicos Islands', 'fr'),
('tc', 'Turks and Caicos Islands', 'nl'),
('tv', 'Tuvalu', 'en'),
('tv', 'Tuvalu', 'fr'),
('tv', 'Tuvalu', 'nl'),
('ug', 'Uganda', 'en'),
('ug', 'Uganda', 'fr'),
('ug', 'Uganda', 'nl'),
('ua', 'Ukraine', 'en'),
('ua', 'Ukraine', 'fr'),
('ua', 'Ukraine', 'nl'),
('ae', 'United Arab Emirates', 'en'),
('ae', 'United Arab Emirates', 'fr'),
('ae', 'United Arab Emirates', 'nl'),
('gb', 'United Kingdom', 'en'),
('gb', 'United Kingdom', 'fr'),
('gb', 'United Kingdom', 'nl'),
('us', 'United States', 'en'),
('us', 'United States', 'fr'),
('us', 'United States', 'nl'),
('um', 'United States Minor Outlying Islands', 'en'),
('um', 'United States Minor Outlying Islands', 'fr'),
('um', 'United States Minor Outlying Islands', 'nl'),
('uy', 'Uruguay', 'en'),
('uy', 'Uruguay', 'fr'),
('uy', 'Uruguay', 'nl'),
('uz', 'Uzbekistan', 'en'),
('uz', 'Uzbekistan', 'fr'),
('uz', 'Uzbekistan', 'nl'),
('vu', 'Vanuatu', 'en'),
('vu', 'Vanuatu', 'fr'),
('vu', 'Vanuatu', 'nl'),
('ve', 'Venezuela, Bolivarian Republic of', 'en'),
('ve', 'Venezuela, Bolivarian Republic of', 'fr'),
('ve', 'Venezuela, Bolivarian Republic of', 'nl'),
('vn', 'Viet Nam', 'en'),
('vn', 'Viet Nam', 'fr'),
('vn', 'Viet Nam', 'nl'),
('vg', 'Virgin Islands, British', 'en'),
('vg', 'Virgin Islands, British', 'fr'),
('vg', 'Virgin Islands, British', 'nl'),
('vi', 'Virgin Islands, U.S.', 'en'),
('vi', 'Virgin Islands, U.S.', 'fr'),
('vi', 'Virgin Islands, U.S.', 'nl'),
('wf', 'Wallis and Futuna', 'en'),
('wf', 'Wallis and Futuna', 'fr'),
('wf', 'Wallis and Futuna', 'nl'),
('eh', 'Western Sahara', 'en'),
('eh', 'Western Sahara', 'fr'),
('eh', 'Western Sahara', 'nl'),
('ye', 'Yemen', 'en'),
('ye', 'Yemen', 'fr'),
('ye', 'Yemen', 'nl'),
('zm', 'Zambia', 'en'),
('zm', 'Zambia', 'fr'),
('zm', 'Zambia', 'nl'),
('zw', 'Zimbabwe', 'en'),
('zw', 'Zimbabwe', 'fr'),
('zw', 'Zimbabwe', 'nl');