<?php

namespace App\Models;

use \Illuminate\Database\Eloquent\Model;
use \App\User;
use App\Models\Quiz\QuizQuestion;
/**
 * Tweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    origin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AccountTypeTranslation extends Model {

    protected $table = 'account_type_translation';
    


}
