<?php

namespace App\Models;


use App\Models\AbstractModels\TranslatableModel;
use \App\User;
use App\Models\Quiz\QuizQuestion;
use Illuminate\Support\Facades\App;


/**
 * Tweet
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    origin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AccountType extends TranslatableModel{

    const ACCOUNT_FREE_KEY          = 'free';
    const ACCOUNT_NUMBER_NO_LIMIT   = -1;
    const ACCOUNT_TYPE       = [
        ['key_name'=>'free','real_price'         => 0,'max_tests'=>1 ,'users_limit' => 1],
        ['key_name'=>'starter','real_price'     => 20,'max_tests'=>2 ,'users_limit' => 2],
        ['key_name'=>'medium','real_price'       => 50,'max_tests'=>20 ,'users_limit' => 10],
        ['key_name'=>'premium','real_price'      => 100,'max_tests'=>-1 ,'users_limit' => -1]
    ];



    protected $table = 'account_type';

    protected $foreignKeyTranslation = 'account_id';
    protected $translateClass = AccountTypeTranslation::class;


    public static function getAccountByKey($keyName){
        return AccountType::where('key_name','=',$keyName)->first();
    }



}
